#PBS -N mps_dscaling
#PBS -l select=1:ncpus=16:mem=60gb:interconnect=fdr,walltime=72:00:00

source ~/bash_setup/packages_qcommunity_ml.sh
export PATH="/home/rshaydu/soft/anaconda3/bin:$PATH"
source activate qcommunity_ml

cd /home/rshaydu/quantum/ibmqxbackend_multilevel/ibmqxbackend/benchmarking/mps_simulator

for d in $(seq 1 30);
do
    ./main.py -q 100 -d $d --save depth_varies_qubits_100.csv
done
